- name: add sonarqube user
  ansible.builtin.user:
    name: sonar

- name: Download sonarqube
  ansible.builtin.get_url:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.5.1.90531.zip
    dest: /opt/sonar

- name: unarchive sonarqube
  ansible.builtin.unarchive:
    src: /opt/sonar
    dest: /sonar
    owner: sonar
    group: sonar
    remote_src: yes