- name: add sonarqube user
  ansible.builtin.user:
    name: sonar

- name: make a directory
  ansible.builtin.file:
    path: /opt/sonarqube
    state: directory

- name: unarchive sonarqube
  ansible.builtin.unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.5.1.90531.zip
    dest: /opt/sonarqube
    remote_src: yes


