- name: copy grafana repo
  ansible.builtin.template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo

- name: Install grafana package
  ansible.builtin.dnf:
    name: grafana
    state: installed

- name: start grafana server
  ansible.builtin.systemd_service:
    name: grafana-server
    state: restarted
    enabled: yes


