- name: make a directory
  ansible.builtin.file:
    path: /opt/actions
    state: directory

- name: make another directory
  ansible.builtin.file:
    path: /opt/act
    state: directory
  become_user: ec2-user