- name: Download  and unarchive Prometheus
  ansible.builtin.unarchive:
    url: https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz
    dest: /opt

