- name: set promt for ci-server
  ansible.builtin.shell: set-prompt ci-server

- name: make a directory
  ansible.builtin.file:
    path: /opt/github-runner
    state: directory
  become_user: ec2-user

- name: Download and unarchive github runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
    dest: /opt/github-runner
    remote_src: yes
  become_user: ec2-user

- name: config runner
  ansible.builtin.shell: /ec2-user/config.sh